language: php

php:
  - 7.1
  - 7.2
  - 7.3

# blocklist
branches:
  except:
  - master
  - develop

before_install:
  - sudo apt-get -qq update
  - yes | pecl install imagick
  - sudo apt-get install -y ghostscript
  - travis_retry composer self-update

install:
  - travis_retry composer update
  
before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate


script:
  - vendor/bin/phpunit

cache:
  directories:
    - node_modules
    - vendor
